### ISSUE TITLE
(localdebugconsole): configuration value `bindHostname` not documented

### ISSUE THREAD

**Issue by jordanjennings** [aws-greengrass/aws-greengrass-localdebugconsole#15]
**Describe the bug**
Documentation bug: the configuration value `bindHostname` is not documented here: https://docs.aws.amazon.com/greengrass/v2/developerguide/local-debug-console-component.html#local-debug-console-component-configuration

**To Reproduce**
N/A

**Expected behavior**
Configuration value `bindHostname` to be documented

**Actual behavior**
No documentation

**Environment**
N/A

**Additional context**
For folks using containerized deployment of the GG nucleus, in order to use the local debug console it has to bind to `0.0.0.0` so that the port can be accessed via docker's port forwarding.

**Comment by MikeDombo** [comment]
Thank you for this feedback. 

We have staged updated documentation for release soon.

Thank you again,
Michael
