### ISSUE TITLE
Changing the bindHostname value does not bind to the correct IP address until the component is restarted

### ISSUE THREAD

**Issue by timmattison** [aws-greengrass/aws-greengrass-localdebugconsole#20]
**Describe the bug**
The `bindHostname` parameter allows the user to bind the local debug console to an IP other than `127.0.0.1`. But when `bindHostname` is set to `0.0.0.0` and the component is redeployed it does not listen on the new IP address until the component (or Greengrass) is restarted.

**To Reproduce**
- Deploy Greengrass with the local debug console and set the `httpsEnabled` configuration value to `false`
- Get the debug password and connect to the UI to validate it is working
- Revise the deployment in the console and add the `bindHostname` configuration value set to `0.0.0.0`
- Get the debug password and attempt to connect to the UI again

**Expected behavior**
The UI should reload on the new IP address

**Actual behavior**
The UI does not reload on the new IP address. If I look at netstat before setting `bindHostname` to `0.0.0.0` I see this:

```
$ netstat -an | grep 144
tcp6       0      0 127.0.0.1:1441          :::*                    LISTEN
tcp6       0      0 127.0.0.1:1442          :::*                    LISTEN
```

After setting `bindHostname` to `0.0.0.0` and redeploying I see this:

```
$ netstat -an | grep 144
tcp6       0      0 :::1442                 :::*                    LISTEN
```

It appears that both listeners close on `127.0.0.1` but only the listener for port 1442 re-opens on `0.0.0.0`.

After restarting Greengrass it looks like this:

```
$ netstat -an | grep 144
tcp6       0      0 :::1441                 :::*                    LISTEN
tcp6       0      0 :::1442                 :::*                    LISTEN
```

**Environment**
 - OS: Ubuntu 20.04 LTS
 - JDK version: openjdk 17.0.2
 - Nucleus version: 2.5.5
 - LocalDebugConsole version: 2.2.3

**Additional context**
This bug causes issues when changing the `bindHostname` configuration value without restarting.

Setting `bindHostname` to `0.0.0.0` is useful testing and developing Greengrass code inside of virtual machines. Some virtualization software (like Vagrant with VirtualBox) can't forward connections if the socket is only bound to `127.0.0.1`.

**Comment by MikeDombo** [comment]
Hi Tim, thanks for reporting this. It is expected and the solution as you found is to restart Greengrass. By definition, if you're using the local debug console then you must have CLI and local access to the Greengrass device; therefore restarting the server is expected to be easily doable.
