### ISSUE TITLE
(LocalDebugConsole): component diagram cut to the right

### ISSUE THREAD

**Issue by massi-ang** [aws-greengrass/aws-greengrass-localdebugconsole#33]
**Describe the bug**
The console diagram seems to be cut to the right

**To Reproduce**
The diagram in the console is cut to the right. This is apparently due to the width sizing of the `<svg>` component being too small. Modifying the sizing manually reveals the missing diagram parts.

![image](https://github.com/aws-greengrass/aws-greengrass-localdebugconsole/assets/38036163/b1e40c42-48ef-421e-b9d5-c12b1e728555)

**Expected behavior**
The diagram is visible in its enterity

**Actual behavior**
Diagram is cut

**Environment**
 - OS: [e.g. Ubuntu 20.04]
 - JDK version: 
 - Nucleus version:
 - LocalDebugConsole version: 2.3.1

**Additional context**
Fix by changing the width to 100% instead of a fixed value and using the css style instead of the `width` keyword.

![image](https://github.com/aws-greengrass/aws-greengrass-localdebugconsole/assets/38036163/90c802d9-7246-4df6-8a84-158de2e477a8)

E.g. what is the impact of the bug?

**Comment by MikeDombo** [comment]
Hi Massi,

Thanks for this. Would you be able to raise a PR to fix it?

**Comment by massi-ang** [comment]
Should be able, yes :-)
