### ISSUE TITLE
Localdebug console allow start button to retry

### ISSUE THREAD

**Issue by psshiner** [aws-greengrass/aws-greengrass-localdebugconsole#6]
**Feature Description**
When there is an error in the component and its marked as broken it is not possible to force a restart

**Use Case**
sometimes during prototypes there are small code errors which cause the component to be marked broken and the console greys out the start button

**Proposed Solution**
Add restart button for when this case occurs to force a retry.

**Other**
Add detailed explanation, stacktraces, related issues, links for us to have context, etc

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
There is a reinstall button, right? That should cover this use case.

**Comment by MikeDombo** [comment]
I'm going to close this since `reinstall` handles this use case. Please reopen if you disagree or need to discuss it more.
